### ISSUE TITLE
Support for newer diffusion models (2.1 and XL) and other questions

### ISSUE THREAD

**Issue by sashaok123** [tfernd/HyperTile#1]
Will the technology support more modern SD2.1 and SDXL models? 
SD1.5 is popular at the moment, but it slows down the development of neural networks and models.

Will the technology conflict (or replace) ToMe? 

And it is not very clear on the consumption of video memory. How much percent will increase the consumption of it? (Approximately as a percentage)

There is also a question about training LoRA models for HyperTile.
Is there any information at this stage on how to do this?!

**Comment by tfernd** [comment]
I need to locate the SDXL layers that takes longer to evaluate, to try tiling it.
Tiling just the attention gives only 1.1 to 1.2 speed-up.

Memory usage is not increased compared to non-tiled version. Its decreases memory usage and decreases time too. win-win.

I'll play with a fork of Kohya-ss that I made a few weeks ago, https://github.com/tfernd/kohya_ss-multiplier.
They use diffusers as back-end, so it should be really simple. Still don't know if that decreases the memory usage by a lot during the backward pass since now the attention is smaller.
