### ISSUE TITLE
HyperTile x ToMe

### ISSUE THREAD

**Issue by Astropulse** [tfernd/HyperTile#3]
I'm curious how this might work with ToMe, as they both accomplish similar tasks. In my own attempt to implement both I found that HyperTile results in much faster speeds, while ToMe seems to have little effect. It's entirely possible my implementation of ToMe was flawed. Attempting to apply ToMe on the tiled attention segments resulted in a slew of issues.

Have you considered how the two may effect or enhance each other?

**Comment by tfernd** [comment]
Kind of similar.
ToMe calculates a score matrix (unnormalized attention) between even and odd índices. Based on the scores it merge some tokens. So it changes the tokens embedding space. This has a detrimental effect with some LoRAs etc.

HyperTile does not modify the tokens. Think of it as a masked attention. Where we mask tokens to be within the same tile window.
So no pre score matrix is needed. No need to fill the attention with zeros. Because we are cleverly reshaping things.

So the vram and speed for that layer is drastically improved by a fourth power of the tile ratio.

**Comment by tfernd** [comment]
Question answered
